FROM golang:alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o client ./cmd/client

FROM alpine:latest

WORKDIR /app

COPY --from=builder /build/client .

CMD ["./client"]
